language: php
php:
  - 7.0

sudo: false

addons:
  chrome: stable
  apt:
    packages:
      - php5-cgi
      - php5-mysql

matrix:
  fast_finish: true

env:
  global:
    - DATABASE='drupal'
    - DB_USERNAME='root'
    - DB_ENCODE='utf8'

mysql:
  database: $DATABASE
  username: $DB_USERNAME
  encoding: $DB_ENCODE

before_script:
  - google-chrome --version
  - /bin/bash scripts/travis.sh

script:
  - composer test
  - drush cex -y
  - /bin/bash scripts/travis-check.sh
