os: linux
arch: arm64-graviton2
group: edge
language: php
php:
  - 7.1

sudo: false

addons:
  chrome: stable
  
services:
  - mysql

matrix:
  fast_finish: true

env:
  global:
    - DATABASE='drupal'
    - DB_USERNAME='root'
    - DB_ENCODE='utf8'

mysql:
  database: $DATABASE
  username: $DB_USERNAME
  encoding: $DB_ENCODE

before_script:
  - google-chrome --version
  - /bin/bash scripts/travis.sh

script:
  - composer test
  - /bin/bash scripts/travis-check.sh
