language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: nightly
    - php: hhvm-nightly

env:
  global:
    - DATABASE='drupal'
    - DB_USERNAME='root'
    - DB_ENCODE='utf8'

mysql:
  database: $DATABASE
  username: $DB_USERNAME
  encoding: $DB_ENCODE

before_script:
  - composer global require drush/drush:dev-master
  - /bin/bash scripts/travis.sh

script:
  - echo "awesome"
