module:
  block: 0
  block_content: 0
  breakpoint: 0
  color: 0
  comment: 0
  config: 0
  contextual: 0
  datetime: 0
  dblog: 0
  editor: 0
  entity_reference: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  hal: 0
  image: 0
  link: 0
  menu_ui: 0
  node: 0
  options: 0
  orkjern_theme_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  rest: 0
  serialization: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  standard: 1000
theme:
  stable: 1
  classy: 1
  seven: 1
  orkjern_theme: 1
