<?php

/**
 * @file
 * Primary module hooks for orkjern_custom module.
 */

use Drupal\Core\Site\Settings;

/**
 * Implements hook_entity_presave().
 */
function orkjern_custom_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  $client = \Drupal::httpClient();
  $user = Settings::get('orkjern_custom_github_user');
  $token = Settings::get('orkjern_custom_github_token');
  $slug = Settings::get('orkjern_custom_notify_slug');
  if (!$user || !$token || !$slug) {
    return;
  }
  try {
    $response = $client->post(sprintf('https://api.github.com/repos/%s/dispatches', $slug), [
      'body' => json_encode(['event_type' => 'i_did_something']),
      'auth' => [
        $user,
        $token,
      ]
    ]);
  }
  catch (\Throwable $e) {

  }
}
